### ISSUE TITLE
<ChannelBlock>.cache is null

### ISSUE THREAD

**Issue by PalmDevs** [BirbJS/Birb#37]
**Describe the bug**
When the client receives channels, the code was unable to set channel caches.
This is due to the [type of the cache property](https://github.com/BirbJS/Birb/blob/main/src/classes/blocks/ChannelBlock.ts#L20) being defaulted to `null!` causing TSC to compile wrong.  
You can check other blocks to see a clear difference.

**To Reproduce**
1. Make sure your testing bot is at least in 1 guild with a channel
2. Connect it to the Discord gateway
3. See errors

**Expected behavior**
Code being able to set channel caches without any errors.

**Errors**
```
TypeError: Cannot read property 'set' of null
    at RefrenceCache.set (....\classes\cache\RefrenceCache.js:77:37)
    at Guild.build (....\classes\Guild.js:231:41)
    at new Guild (....\classes\Guild.js:198:14)
    at Object.GUILD_CREATE [as default] (....\classes\websocket\handlers\GUILD_CREATE.js:19:17)
    
    ... (more error stacks are not useful anymore)
```

**Platform**
- OS: Windows 10 x64
- Node version: v16.6.0
- Birb.JS version: 1.0.0-pre.5

**Comment by knokbak** [comment]
fixed in pr #36
